/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAchievementsRouteImport } from './routes/app.achievements'
import { Route as AppBookmarksRouteImport } from './routes/app.bookmarks'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppCommunityRouteImport } from './routes/app.community'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppFlashcardsRouteImport } from './routes/app.flashcards'
import { Route as AppGraphRouteImport } from './routes/app.graph'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppMindmapsRouteImport } from './routes/app.mindmaps'
import { Route as AppNotesRouteImport } from './routes/app.notes'
import { Route as AppPathsRouteImport } from './routes/app.paths'
import { Route as AppQuizzesRouteImport } from './routes/app.quizzes'
import { Route as AppSettingsRouteImport } from './routes/app.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppBookmarksRoute = AppBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFlashcardsRoute = AppFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AppRoute,
} as any)
const AppGraphRoute = AppGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppMindmapsRoute = AppMindmapsRouteImport.update({
  id: '/mindmaps',
  path: '/mindmaps',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppPathsRoute = AppPathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesRoute = AppQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/achievements': typeof AppAchievementsRoute
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/chat': typeof AppChatRoute
  '/app/community': typeof AppCommunityRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/graph': typeof AppGraphRoute
  '/app/library': typeof AppLibraryRoute
  '/app/mindmaps': typeof AppMindmapsRoute
  '/app/notes': typeof AppNotesRoute
  '/app/paths': typeof AppPathsRoute
  '/app/quizzes': typeof AppQuizzesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/chat': typeof AppChatRoute
  '/app/community': typeof AppCommunityRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/graph': typeof AppGraphRoute
  '/app/library': typeof AppLibraryRoute
  '/app/mindmaps': typeof AppMindmapsRoute
  '/app/notes': typeof AppNotesRoute
  '/app/paths': typeof AppPathsRoute
  '/app/quizzes': typeof AppQuizzesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/achievements': typeof AppAchievementsRoute
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/chat': typeof AppChatRoute
  '/app/community': typeof AppCommunityRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/graph': typeof AppGraphRoute
  '/app/library': typeof AppLibraryRoute
  '/app/mindmaps': typeof AppMindmapsRoute
  '/app/notes': typeof AppNotesRoute
  '/app/paths': typeof AppPathsRoute
  '/app/quizzes': typeof AppQuizzesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/achievements'
    | '/app/bookmarks'
    | '/app/chat'
    | '/app/community'
    | '/app/dashboard'
    | '/app/flashcards'
    | '/app/graph'
    | '/app/library'
    | '/app/mindmaps'
    | '/app/notes'
    | '/app/paths'
    | '/app/quizzes'
    | '/app/settings'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/achievements'
    | '/app/bookmarks'
    | '/app/chat'
    | '/app/community'
    | '/app/dashboard'
    | '/app/flashcards'
    | '/app/graph'
    | '/app/library'
    | '/app/mindmaps'
    | '/app/notes'
    | '/app/paths'
    | '/app/quizzes'
    | '/app/settings'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/achievements'
    | '/app/bookmarks'
    | '/app/chat'
    | '/app/community'
    | '/app/dashboard'
    | '/app/flashcards'
    | '/app/graph'
    | '/app/library'
    | '/app/mindmaps'
    | '/app/notes'
    | '/app/paths'
    | '/app/quizzes'
    | '/app/settings'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/achievements': {
      id: '/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookmarks': {
      id: '/app/bookmarks'
      path: '/bookmarks'
      fullPath: '/app/bookmarks'
      preLoaderRoute: typeof AppBookmarksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community': {
      id: '/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/flashcards': {
      id: '/app/flashcards'
      path: '/flashcards'
      fullPath: '/app/flashcards'
      preLoaderRoute: typeof AppFlashcardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/graph': {
      id: '/app/graph'
      path: '/graph'
      fullPath: '/app/graph'
      preLoaderRoute: typeof AppGraphRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mindmaps': {
      id: '/app/mindmaps'
      path: '/mindmaps'
      fullPath: '/app/mindmaps'
      preLoaderRoute: typeof AppMindmapsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/paths': {
      id: '/app/paths'
      path: '/paths'
      fullPath: '/app/paths'
      preLoaderRoute: typeof AppPathsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quizzes': {
      id: '/app/quizzes'
      path: '/quizzes'
      fullPath: '/app/quizzes'
      preLoaderRoute: typeof AppQuizzesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppBookmarksRoute: typeof AppBookmarksRoute
  AppChatRoute: typeof AppChatRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFlashcardsRoute: typeof AppFlashcardsRoute
  AppGraphRoute: typeof AppGraphRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppMindmapsRoute: typeof AppMindmapsRoute
  AppNotesRoute: typeof AppNotesRoute
  AppPathsRoute: typeof AppPathsRoute
  AppQuizzesRoute: typeof AppQuizzesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppBookmarksRoute: AppBookmarksRoute,
  AppChatRoute: AppChatRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFlashcardsRoute: AppFlashcardsRoute,
  AppGraphRoute: AppGraphRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppMindmapsRoute: AppMindmapsRoute,
  AppNotesRoute: AppNotesRoute,
  AppPathsRoute: AppPathsRoute,
  AppQuizzesRoute: AppQuizzesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
